name-template: 'releases/v$RESOLVED_VERSION'
tag-template: 'releases/v$RESOLVED_VERSION'
commitish: 'production'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'hotfix'
  - title: '🪡 Small Changes'
    label: 'small-changes'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'hotfix'
  default: patch
autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
      - '/documentations{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
      - '/hotfix\/.+/'
    title:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
      - '/hotfix\/.+/'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
exclude-labels:
  - 'skip-changelog'
template: |
  # Changes

  $CHANGES

  -------
  Contributors: $CONTRIBUTORS
